[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
]


[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false


[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.sshmoria]
animation = "fromTop"
command = "kitty --class kitty-ssh -e ssh root@10.11.18.100"
class = "kitty-ssh"
size = "75% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"

[scratchpads.obsidian]
animation = "fromTop"
command = "obsidian 'obsidian://open?vault=Vortex&file=00-Hub%2F%F0%9F%9A%80%20Dashboard%20Principal'"
class = "obsidian"
size = "85% 70%"
lazy = true

